export enum SectionType {
    // Account
    ACCOUNT_SIG_ALGORITHM = 0,
    ACCOUNT_PUBLIC_KEY = 1,
    ACCOUNT_TOKEN_ISSUANCE = 2,
    ACCOUNT_CREATION = 3,
    ACCOUNT_TRANSFER = 4,
    ACCOUNT_SIGNATURE = 5,

    // Organization
    ORG_SIG_ALGORITHM = 100,
    ORG_PUBLIC_KEY = 101,
    ORG_DESCRIPTION = 102,
    ORG_SERVER = 103,
    ORG_SIGNATURE = 104,

    // Application
    APP_SIG_ALGORITHM = 200,
    APP_DECLARATION = 201,
    APP_DESCRIPTION = 202,
    APP_SIGNATURE = 203,

    // Application Ledger
    APP_LEDGER_SIG_ALGORITHM = 300,
    APP_LEDGER_DECLARATION = 301,
    APP_LEDGER_ACTOR_CREATION = 302,
    APP_LEDGER_CHANNEL_CREATION = 303,
    APP_LEDGER_SHARED_SECRET = 304,
    APP_LEDGER_CHANNEL_INVITATION = 305,
    APP_LEDGER_ACTOR_SUBSCRIPTION = 306,
    APP_LEDGER_PUBLIC_CHANNEL_DATA = 307,
    APP_LEDGER_PRIVATE_CHANNEL_DATA = 308,
    APP_LEDGER_AUTHOR = 309,
    APP_LEDGER_ENDORSER = 310,
    APP_LEDGER_ENDORSER_SIGNATURE = 311,
    APP_LEDGER_AUTHOR_SIGNATURE = 312,
}


