export enum SectionType {
    // Protocol
    PROTOCOL_SIG_SCHEME = 0x00,
    PROTOCOL_PUBLIC_KEY = 0x01,
    PROTOCOL_PROTOCOL_UPDATE = 0x02,
    PROTOCOL_NODE_UPDATE = 0x03,
    PROTOCOL_SIGNATURE = 0x04,

    // Account
    ACCOUNT_SIG_SCHEME = 0x10,
    ACCOUNT_PUBLIC_KEY = 0x11,
    ACCOUNT_TOKEN_ISSUANCE = 0x12,
    ACCOUNT_CREATION = 0x13,
    ACCOUNT_TRANSFER = 0x14,
    ACCOUNT_SIGNATURE = 0x15,

    // Validator node
    VN_SIG_SCHEME = 0x20,
    VN_DECLARATION = 0x21,
    VN_DESCRIPTION = 0x22,
    VN_RPC_ENDPOINT = 0x23,
    VN_NETWORK_INTEGRATION = 0x24,
    VN_SIGNATURE = 0x25,

    // Organization
    ORG_SIG_SCHEME = 0x30,
    ORG_PUBLIC_KEY = 0x31,
    ORG_DESCRIPTION = 0x32,
    ORG_SERVER = 0x33,
    ORG_SIGNATURE = 0x34,

    // Application
    APP_SIG_SCHEME = 0x40,
    APP_DECLARATION = 0x41,
    APP_DESCRIPTION = 0x42,
    APP_SIGNATURE = 0x43,

    // Application Ledger
    APP_LEDGER_ALLOWED_SIG_SCHEMES = 0x50,
    APP_LEDGER_ALLOWED_PKE_SCHEMES = 0x51,
    APP_LEDGER_DECLARATION = 0x52,
    APP_LEDGER_ACTOR_CREATION = 0x53,
    APP_LEDGER_CHANNEL_CREATION = 0x54,
    APP_LEDGER_SHARED_SECRET = 0x55,
    APP_LEDGER_CHANNEL_INVITATION = 0x56,
    APP_LEDGER_ACTOR_SUBSCRIPTION = 0x57,
    APP_LEDGER_PUBLIC_CHANNEL_DATA = 0x58,
    APP_LEDGER_PRIVATE_CHANNEL_DATA = 0x59,
    APP_LEDGER_AUTHOR = 0x5A,
    APP_LEDGER_ENDORSER = 0x5B,
    APP_LEDGER_ENDORSER_SIGNATURE = 0x5C,
    APP_LEDGER_AUTHOR_SIGNATURE = 0x5D,
}
