export enum SectionType {
    // Account
    ACCOUNT_SIG_ALGORITHM = 0,
    ACCOUNT_PUBLIC_KEY = 1,
    ACCOUNT_TOKEN_ISSUANCE = 2,
    ACCOUNT_CREATION = 3,
    ACCOUNT_TRANSFER = 4,
    ACCOUNT_SIGNATURE = 5,

    // Organization
    ORG_SIG_ALGORITHM = 10,
    ORG_PUBLIC_KEY = 11,
    ORG_DESCRIPTION = 12,
    ORG_SERVER = 13,
    ORG_SIGNATURE = 14,

    // Application
    APP_SIG_ALGORITHM = 20,
    APP_DECLARATION = 21,
    APP_DESCRIPTION = 22,
    APP_SIGNATURE = 23,

    // Application Ledger
    APP_LEDGER_ALLOWED_SIG_ALGORITHMS = 30,
    APP_LEDGER_ALLOWED_PKE_ALGORITHMS = 31,
    APP_LEDGER_DECLARATION = 32,
    APP_LEDGER_ACTOR_CREATION = 33,
    APP_LEDGER_CHANNEL_CREATION = 34,
    APP_LEDGER_SHARED_SECRET = 35,
    APP_LEDGER_CHANNEL_INVITATION = 36,
    APP_LEDGER_ACTOR_SUBSCRIPTION = 37,
    APP_LEDGER_PUBLIC_CHANNEL_DATA = 38,
    APP_LEDGER_PRIVATE_CHANNEL_DATA = 39,
    APP_LEDGER_AUTHOR = 40,
    APP_LEDGER_ENDORSER = 41,
    APP_LEDGER_ENDORSER_SIGNATURE = 42,
    APP_LEDGER_AUTHOR_SIGNATURE = 43,
}
