import {VB_ACCOUNT, VB_APP_LEDGER, VB_APPLICATION, VB_ORGANIZATION, VB_VALIDATOR_NODE} from "../constants/chain";

export enum VirtualBlockchainType {
    ACCOUNT_VIRTUAL_BLOCKCHAIN = VB_ACCOUNT,
    NODE_VIRTUAL_BLOCKCHAIN = VB_VALIDATOR_NODE,
    APPLICATION_VIRTUAL_BLOCKCHAIN = VB_APPLICATION,
    ORGANIZATION_VIRTUAL_BLOCKCHAIN = VB_ORGANIZATION,
    APP_LEDGER_VIRTUAL_BLOCKCHAIN = VB_APP_LEDGER,
}

/*
export const VB_ACCOUNT        = 0;
export const VB_VALIDATOR_NODE = 1;
export const VB_ORGANIZATION   = 2;
export const VB_APPLICATION    = 3;
export const VB_APP_LEDGER     = 4;

 */
